### ISSUE TITLE
lm_eval用法

### ISSUE THREAD

**Issue by fmk345** [MrGGLS/BlockPruner#1]
我在import lm_eval时，会在以下阶段：2024-11-30:09:36:09,691 INFO     [utils.py:149] Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
2024-11-30:09:36:09,691 INFO     [utils.py:162] NumExpr defaulting to 16 threads.然后一直卡着，请问有没有什么解决办法，是因为服务器上面没有网络代理所导致的吗？

**Comment by MrGGLS** [comment]
可能是你的CPU不太行，可以查看下是不是有什么程序占了太多CPU资源（线程，内存啥的）

**Comment by fmk345** [comment]
非常感谢回复，昨天给服务器挂了一个代理，成功运行了一次，后来又不行了，请问用lm_eval这个包的时候需要给服务器挂代理吗？因为里面好像有从huggingface上面载入exact-match这一步，还有后面测试的任务的数据集也是线上载入的有没有放入本地的办法呢

**Comment by MrGGLS** [comment]
可以在运行脚本的开头加上下面的镜像代理
```bash
export HF_ENDPOINT=https://hf-mirror.com
```
如果还是有数据集下载不了的问题，可以查看报错时（connection timeout）对应的代码位置，找到加载数据集的链接替换成本地数据集路径即可。

**Comment by fmk345** [comment]
谢谢，非常感谢

**Comment by fmk345** [comment]
请问在使用slicegpt时，比如对llama2-7b进行剪枝，slicegpt的代码剪枝完成后会形成一个.pt文件，这个文件在进行lm_eval时会显示不适配，请问您有没有什么解决办法

**Comment by MrGGLS** [comment]
可以去看slicegpt的源码，我是从它那里改的

**Comment by fmk345** [comment]
好的，非常感谢
